INSERT INTO APP.PROJET (ID, DATEDEB, DESCRIPTION, NOM)
	VALUES (1, CURRENT_DATE, '1e projet', 'Projet 1');
	
INSERT INTO APP.PROJET (ID, DATEDEB, DESCRIPTION, NOM) 
	VALUES (2, CURRENT_DATE, '2e projet', 'Projet 2');
	
INSERT INTO APP.PROJET (ID, DATEDEB, DESCRIPTION, NOM) 
	VALUES (3, CURRENT_DATE, '3e projet', 'Projet 3');
	
INSERT INTO APP.PROJET (ID, DATEDEB, DESCRIPTION, NOM) 
	VALUES (4, CURRENT_DATE, '4e projet', 'Projet 4');
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (1, '1', CURRENT_TIMESTAMP, '1ere tache', 0, 'Tache1', 10, null, 0, NULL, 1);	
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (2, '0', CURRENT_TIMESTAMP, '2e tache', 1, 'Tache2', 20, null, 0, NULL, 1);
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (3, '1', CURRENT_TIMESTAMP, '3e tache', 2, 'Tache3', 30, null, 0, NULL, 1);
		
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (4, '0', CURRENT_TIMESTAMP, '4e tache', 0, 'Tache4', 40, null, 0, NULL, 1);
		
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (5, '1', CURRENT_TIMESTAMP, '5e tache', 1, 'Tache5', 50, null, 0, NULL, 2);
		
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (6, '0', CURRENT_TIMESTAMP, '6e tache', 2, 'Tache6', 60, null, 0, NULL, 2);
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (7, '1', CURRENT_TIMESTAMP, '7e tache', 0, 'Tache7', 70, null, 0, NULL, 3);
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (8, '0', CURRENT_TIMESTAMP, '8e tache', 0, 'Tache8', 80, null, 0, NULL, 4);
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (9, '1', CURRENT_TIMESTAMP, '9e tache', 2, 'Tache9', 90, null, 0, NULL, 1);
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (10, '0', CURRENT_TIMESTAMP, '10e tache', 0, 'Tache10', 100, 143, 0, NULL, 1);
	
INSERT INTO APP.TACHE (ID, ARCHIVE, DATEDEB, DESCRIPTION, IMPORTANCE, NOM, POURCENTAGE, REVISION, TEMPSPASSESURTACHE, TIMERLAUNCHED, PROJET) 
	VALUES (11, '0', CURRENT_TIMESTAMP, '11e tache', 0, 'Tache11', 0, null, 0, NULL, 1);
	
INSERT INTO APP.MEMBRE (ID, LOGIN, MAIL, NOM, PASSWORD, PRENOM) VALUES (1, 'mbr', 'mbr@mbr.be', 'Nom', 'mbr', 'Prénom');

UPDATE APP.SEQUENCE SET SEQ_COUNT=4 where SEQ_NAME LIKE 'Projet';

UPDATE APP.SEQUENCE SET SEQ_COUNT=11 where SEQ_NAME LIKE 'Tache';

UPDATE APP.SEQUENCE SET SEQ_COUNT=1 where SEQ_NAME LIKE 'Membre';
